<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Zend Application</title>
    <?php // echo $this->headLink()->appendStylesheet('styles/styles.css')?>
    <?php // echo $this->headLink()->appendStylesheet('styles/sites.css')?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/foundation.css')) ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/app.css')) ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl('/css/ie.css', 'screen', 'if lt IE 9')) ?>
    <?php //echo $this->headScript()->appendFile('http://html5shiv.googlecode.com/svn/trunk/html5.js', $type = 'text/javascript', $attrs = array('conditional' => 'lt IE 9'));?>
    <?php //echo $this->headScript()->appendFile(' https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js', $type='text/javascript');?>
</head>
<body>   
       <div class="row">
	<div class="twelve columns white-background">
            <h5>Crud</h5>
            <p>Versi 001</p>
            <hr />
            <ul class="menu">
                <li><a href="<?php echo $this->url(array('controller'=>'Mahasiswa','action'=>'index'))?>">Home</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'Multiinsert','action'=>'index'))?>">Add Multi</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'Mahasiswa','action'=>'editmulti'))?>">Edit Multi</a></li>
                <li><a href="<?php echo $this->url(array('controller'=>'Login','action'=>'logout'))?>">Logout</a></li>

            </ul>
            <hr/>
            <div class="white-background">
            <?php echo $this->layout()->content ?>
            <hr />
            </div>
            <div id="footer"><p align="center">Copyright</p></div>
            
	</div>
    
    
</div>

</body>
</html>
    